version: "3"

services:
  frontend:
    tty: true
    stdin_open: true
    build: ./frontend/docGPT/
    container_name: frontend-container
    volumes:
      - ./frontend/docGPT/src:/app/src:ro
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true #Necesario para usuarios con windows

  backend:
    build: ./backend
    restart: always
    container_name: backend-container
    volumes:
      - ./backend:/backend:ro
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=${NODE_ENV}
